-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.vacancies
(
    id bigint NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    salary_from numeric(10, 2),
    salary_to numeric(10, 2),
    currency character varying(10) COLLATE pg_catalog."default",
    date date,
    key_skills text COLLATE pg_catalog."default",
    city_id bigint,
    employer_id bigint,
    exp_id integer,
    fmt_id integer,
    grade_id integer,
    role_id integer,
    CONSTRAINT vacancies_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    role_id integer NOT NULL,
    role character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public.grade
(
    grade_id integer NOT NULL,
    grade character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT grade_pkey PRIMARY KEY (grade_id)
);

CREATE TABLE IF NOT EXISTS public.format
(
    fmt_id integer NOT NULL,
    fmt character varying(15) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT format_pkey PRIMARY KEY (fmt_id)
);

CREATE TABLE IF NOT EXISTS public.experience
(
    exp_id integer NOT NULL,
    exp character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT experience_pkey PRIMARY KEY (exp_id)
);

CREATE TABLE IF NOT EXISTS public.employers
(
    employer_id integer NOT NULL,
    name_employer character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT employers_pkey PRIMARY KEY (employer_id)
);

CREATE TABLE IF NOT EXISTS public.cities
(
    city_id integer NOT NULL,
    name_city character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cities_pkey PRIMARY KEY (city_id)
);

ALTER TABLE IF EXISTS public.vacancies
    ADD CONSTRAINT cities FOREIGN KEY (city_id)
    REFERENCES public.cities (city_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vacancies
    ADD CONSTRAINT employers FOREIGN KEY (employer_id)
    REFERENCES public.employers (employer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vacancies
    ADD CONSTRAINT experience FOREIGN KEY (exp_id)
    REFERENCES public.experience (exp_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vacancies
    ADD CONSTRAINT format FOREIGN KEY (fmt_id)
    REFERENCES public.format (fmt_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vacancies
    ADD CONSTRAINT grade FOREIGN KEY (grade_id)
    REFERENCES public.grade (grade_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vacancies
    ADD CONSTRAINT role FOREIGN KEY (role_id)
    REFERENCES public.roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;